# Generate boiler plate code for Python 101 git workshop.
# Use users exported from Moodle as .csv.

import csv
import sys
from unidecode import unidecode

if len(sys.argv) != 2:
    print("Usage: python3 generate.py students_csv")
    exit(1)

def generate_test_code(function_call, code_name, full_name):
    test_code = ''
    test_code += f"\ndef test_{code_name}():\n"
    test_code += f"\tyour_name = {function_call}\n"
    test_code += f"\tif your_name == 'missing':\n"
    test_code += f"\t\treturn\n"
    test_code += f"\tassert your_name == '{full_name}', 'Did you spell your name correctly?'\n"
    return test_code

def generate_code(code_name):
    return (f'greet_{code_name}()', f"def greet_{code_name}():\n\treturn 'missing'\n\n")

with open(sys.argv[1]) as f, open('collaboration.py', 'w') as colab, open('test_collaboration.py', 'w') as test:
    warning = '# This file is autogenerated. Only students should edit.\n'
    warning += '# Add your full name from Moodle to your function.\n\n'
    defitions = ''
    main_body = "if __name__ == '__main__':\n\tstudents = []\n"

    test_cases = '# This file is autogenerated. Do not edit.\n'
    test_cases += '# -*- coding: utf-8 -*-\n\n'
    test_cases += 'from collaboration import *\n'

    skip_header = True
    for student in csv.reader(f, delimiter=','):

        if skip_header:
            skip_header = False
            continue

        full_name = student[0] + ' ' + student[1]
        code_name = unidecode(full_name.lower().replace('-', '_').replace(' ', '_'))

        function_call, code = generate_code(code_name)
        defitions += code
        main_body += '\tstudents += [' + function_call + ']\n'

        test_cases += generate_test_code(function_call, code_name, full_name)
    
    main_body += "\tnot_missing = lambda i: i != 'missing'\n"
    main_body += """\tprint('\\n'.join(filter(not_missing, students)))\n"""

    colab.write(warning)
    colab.write(defitions)
    colab.write(main_body)

    test.write(test_cases)
