# This file is autogenerated. Only students should edit.
# Add your full name from Moodle to your function.

def greet_bogdan_andrei_albescu():
	return 'missing'

def greet_serban_andreea():
	return 'missing'

def greet_matei_andreea_gabriela():
	return 'missing'

def greet_calcan_andrei():
	return 'missing'

def greet_draica_andrei():
	return 'missing'

def greet_ivascu_andrei():
	return 'missing'

def greet_spoiala_andrei_cristian():
	return 'missing'

def greet_dragomir_andrei_mihai():
	return 'missing'

def greet_david_anghel():
	return 'missing'

def greet_andrei_daniel_anghelescu():
	return 'missing'

def greet_miruna_elena_banu():
	return 'missing'

def greet_sorin_petrut_barbu():
	return 'missing'

def greet_mihnea_branzeu():
	return 'missing'

def greet_eduard_robert_paul_brasoveanu():
	return 'missing'

def greet_darius_brinzan():
	return 'missing'

def greet_theodor_ioan_buliga():
	return 'missing'

def greet_razvan_burlacu():
	return 'missing'

def greet_iustina_caramida():
	return 'missing'

def greet_maria_andreea_chirnogeanu():
	return 'missing'

def greet_diana_iulia_ciocoiu():
	return 'missing'

def greet_diana_cismaru():
	return 'missing'

def greet_sorin_conea():
	return 'missing'

def greet_victorita_marinela_cotoi():
	return 'missing'

def greet_avram_cristian_stefan():
	return 'missing'

def greet_ionescu_dan_andrei():
	return 'missing'

def greet_ciobanu_daria():
	return 'missing'

def greet_cristian_descultu():
	return 'missing'

def greet_ene_diana():
	return 'missing'

def greet_ciocoiu_diana_iulia():
	return 'missing'

def greet_calipolitis_dimitri():
	return 'missing'

def greet_bianca_nicola_dragomir():
	return 'missing'

def greet_daniela_alexandra_dragusin():
	return 'missing'

def greet_andreea_drehuta():
	return 'Andreea Drehuta'

def greet_bogdan_dumitrescu():
	return 'missing'

def greet_rares_dumitrescu():
	return 'missing'

def greet_diana_dutica():
	return 'missing'

def greet_motrogan_elena_alexandra():
	return 'missing'

def greet_vlad_gheorghiu():
	return 'missing'

def greet_teodora_grecu():
	return 'missing'

def greet_armand_gabriel_hangu():
	return 'missing'

def greet_hritcu_mesenschi_iasmina():
	return 'missing'

def greet_aradoaie_ioana_maria():
	return 'missing'

def greet_ionut_ionescu():
	return 'missing'

def greet_andreea_istrate():
	return 'missing'

def greet_mihaicuta_iulia():
	return 'missing'

def greet_iustin_ivan():
	return 'missing'

def greet_nicoara_laura_elena():
	return 'missing'

def greet_gabriela_limberea():
	return 'missing'

def greet_lidia_elena_manea():
	return 'missing'

def greet_vlad_manolache():
	return 'missing'

def greet_tudor_marculescu():
	return 'missing'

def greet_neagu_marian_claudiu():
	return 'missing'

def greet_pavel_mateescu():
	return 'missing'

def greet_alexandra_matei():
	return 'missing'

def greet_patrascu_matei():
	return 'missing'

def greet_barbu_mihaela_daniela():
	return 'missing'

def greet_paraschiva_mihai():
	return 'missing'

def greet_leahu_morie_robert_andrei():
	return 'missing'

def greet_robert_ionut_nastase():
	return 'missing'

def greet_vlad_negoita():
	return 'missing'

def greet_radu_nichita():
	return 'missing'

def greet_mara_ioana_nicolae():
	return 'missing'

def greet_irina_cristina_nita():
	return 'missing'

def greet_tarik_ilhan_omer():
	return 'missing'

def greet_mihai_para():
	return 'missing'

def greet_catalin_ciprian_pasare():
	return 'missing'

def greet_mihaicuta_paul_gabriel():
	return 'missing'

def greet_bianca_popa():
	return 'missing'

def greet_andreea_povarna():
	return 'missing'

def greet_diana_preda():
	return 'missing'

def greet_george_raducanu():
	return 'missing'

def greet_lavinia_maria_raduta():
	return 'missing'

def greet_beatris_ranja():
	return 'missing'

def greet_popa_razvan_mihai():
	return 'missing'

def greet_raluca_rizea():
	return 'missing'

def greet_danila_robert():
	return 'missing'

def greet_danila_robert():
	return 'missing'

def greet_grancsa_robert():
	return 'missing'

def greet_untea_robert():
	return 'missing'

def greet_popa_sebastian():
	return 'missing'

def greet_severin_sebastian():
	return 'missing'

def greet_madalin_serbu():
	return 'missing'

def greet_andreea_sima():
	return 'missing'

def greet_leu_dobre_simona():
	return 'missing'

def greet_andreea_cristina_stan():
	return 'missing'

def greet_vlad_stanciu():
	return 'missing'

def greet_mihaela_cristina_stavarache():
	return 'missing'

def greet_ioana_stefan():
	return 'missing'

def greet_alexandru_valentin_stefanescu():
	return 'missing'

def greet_dumitru_bianca_stefania():
	return 'missing'

def greet_andrei_roberto_stoica():
	return 'missing'

def greet_grecu_teodora():
	return 'missing'

def greet_paiu_teofil():
	return 'missing'

def greet_mihalea_tiberiu_marian():
	return 'missing'

def greet_marcu_tudor():
	return 'missing'

def greet_andreea_tudorache():
	return 'missing'

def greet_stefania_tudorancea():
	return 'missing'

def greet_stefania_tudorancea():
	return 'missing'

def greet_andrei_tulpan():
	return 'missing'

def greet_andrei_vasilescu():
	return 'missing'

def greet_mihnea_andrei_vasilescu():
	return 'missing'

def greet_alexandru_nicolae_vladut():
	return 'missing'

def greet_andrei_laurentiu_olteanu():
	return 'missing'

if __name__ == '__main__':
	students = []
	students += [greet_bogdan_andrei_albescu()]
	students += [greet_serban_andreea()]
	students += [greet_matei_andreea_gabriela()]
	students += [greet_calcan_andrei()]
	students += [greet_draica_andrei()]
	students += [greet_ivascu_andrei()]
	students += [greet_spoiala_andrei_cristian()]
	students += [greet_dragomir_andrei_mihai()]
	students += [greet_david_anghel()]
	students += [greet_andrei_daniel_anghelescu()]
	students += [greet_miruna_elena_banu()]
	students += [greet_sorin_petrut_barbu()]
	students += [greet_mihnea_branzeu()]
	students += [greet_eduard_robert_paul_brasoveanu()]
	students += [greet_darius_brinzan()]
	students += [greet_theodor_ioan_buliga()]
	students += [greet_razvan_burlacu()]
	students += [greet_iustina_caramida()]
	students += [greet_maria_andreea_chirnogeanu()]
	students += [greet_diana_iulia_ciocoiu()]
	students += [greet_diana_cismaru()]
	students += [greet_sorin_conea()]
	students += [greet_victorita_marinela_cotoi()]
	students += [greet_avram_cristian_stefan()]
	students += [greet_ionescu_dan_andrei()]
	students += [greet_ciobanu_daria()]
	students += [greet_cristian_descultu()]
	students += [greet_ene_diana()]
	students += [greet_ciocoiu_diana_iulia()]
	students += [greet_calipolitis_dimitri()]
	students += [greet_bianca_nicola_dragomir()]
	students += [greet_daniela_alexandra_dragusin()]
	students += [greet_andreea_drehuta()]
	students += [greet_bogdan_dumitrescu()]
	students += [greet_rares_dumitrescu()]
	students += [greet_diana_dutica()]
	students += [greet_motrogan_elena_alexandra()]
	students += [greet_vlad_gheorghiu()]
	students += [greet_teodora_grecu()]
	students += [greet_armand_gabriel_hangu()]
	students += [greet_hritcu_mesenschi_iasmina()]
	students += [greet_aradoaie_ioana_maria()]
	students += [greet_ionut_ionescu()]
	students += [greet_andreea_istrate()]
	students += [greet_mihaicuta_iulia()]
	students += [greet_iustin_ivan()]
	students += [greet_nicoara_laura_elena()]
	students += [greet_gabriela_limberea()]
	students += [greet_lidia_elena_manea()]
	students += [greet_vlad_manolache()]
	students += [greet_tudor_marculescu()]
	students += [greet_neagu_marian_claudiu()]
	students += [greet_pavel_mateescu()]
	students += [greet_alexandra_matei()]
	students += [greet_patrascu_matei()]
	students += [greet_barbu_mihaela_daniela()]
	students += [greet_paraschiva_mihai()]
	students += [greet_leahu_morie_robert_andrei()]
	students += [greet_robert_ionut_nastase()]
	students += [greet_vlad_negoita()]
	students += [greet_radu_nichita()]
	students += [greet_mara_ioana_nicolae()]
	students += [greet_irina_cristina_nita()]
	students += [greet_tarik_ilhan_omer()]
	students += [greet_mihai_para()]
	students += [greet_catalin_ciprian_pasare()]
	students += [greet_mihaicuta_paul_gabriel()]
	students += [greet_bianca_popa()]
	students += [greet_andreea_povarna()]
	students += [greet_diana_preda()]
	students += [greet_george_raducanu()]
	students += [greet_lavinia_maria_raduta()]
	students += [greet_beatris_ranja()]
	students += [greet_popa_razvan_mihai()]
	students += [greet_raluca_rizea()]
	students += [greet_danila_robert()]
	students += [greet_danila_robert()]
	students += [greet_grancsa_robert()]
	students += [greet_untea_robert()]
	students += [greet_popa_sebastian()]
	students += [greet_severin_sebastian()]
	students += [greet_madalin_serbu()]
	students += [greet_andreea_sima()]
	students += [greet_leu_dobre_simona()]
	students += [greet_andreea_cristina_stan()]
	students += [greet_vlad_stanciu()]
	students += [greet_mihaela_cristina_stavarache()]
	students += [greet_ioana_stefan()]
	students += [greet_alexandru_valentin_stefanescu()]
	students += [greet_dumitru_bianca_stefania()]
	students += [greet_andrei_roberto_stoica()]
	students += [greet_grecu_teodora()]
	students += [greet_paiu_teofil()]
	students += [greet_mihalea_tiberiu_marian()]
	students += [greet_marcu_tudor()]
	students += [greet_andreea_tudorache()]
	students += [greet_stefania_tudorancea()]
	students += [greet_stefania_tudorancea()]
	students += [greet_andrei_tulpan()]
	students += [greet_andrei_vasilescu()]
	students += [greet_mihnea_andrei_vasilescu()]
	students += [greet_alexandru_nicolae_vladut()]
	students += [greet_andrei_laurentiu_olteanu()]
	not_missing = lambda i: i != 'missing'

	print('Here are some awesome people:\n')
	print('\n'.join(filter(not_missing, students)))
	print('\nKudos to you!')
