# This file is autogenerated. Only students should edit.
# Add your full name from Moodle to your function.

def greet_laurentiu_olteanu():
	return 'Laurentiu Olteanu incapabilul'

def greet_razvan_matisan():
	return 'missing'

def greet_mara_nicolae():
	return 'missing'

def greet_diana_dutica():
	return 'missing'

def greet_radu_chivereanu():
	return 'missing'

def greet_radu_minea():
	return 'missing'

def greet_pavel_mateescu():
	return 'missing'

if __name__ == '__main__':
	students = []
	students += [greet_laurentiu_olteanu()]
	students += [greet_razvan_matisan()]
	students += [greet_mara_nicolae()]
	students += [greet_diana_dutica()]
	students += [greet_radu_chivereanu()]
	students += [greet_radu_minea()]
	students += [greet_pavel_mateescu()]
	not_missing = lambda i: i != 'missing'
	print('\n'.join(filter(not_missing, students)))
