# This file is autogenerated. Do not edit.
# -*- coding: utf-8 -*-

from collaboration import *

def test_bianca_andrei():
	your_name = greet_bianca_andrei()
	if your_name == 'missing':
		return
	assert your_name == 'Bianca Andrei', 'Did you spell your name correctly?'

def test_petrea_andrei():
	your_name = greet_petrea_andrei()
	if your_name == 'missing':
		return
	assert your_name == 'Petrea Andrei', 'Did you spell your name correctly?'

def test_george_leonard_batca():
	your_name = greet_george_leonard_batca()
	if your_name == 'missing':
		return
	assert your_name == 'George Leonard Bâtcă', 'Did you spell your name correctly?'

def test_elena_catalina_bogdan():
	your_name = greet_elena_catalina_bogdan()
	if your_name == 'missing':
		return
	assert your_name == 'Elena-Catalina Bogdan', 'Did you spell your name correctly?'

def test_alexandru_calciu():
	your_name = greet_alexandru_calciu()
	if your_name == 'missing':
		return
	assert your_name == 'Alexandru Calciu', 'Did you spell your name correctly?'

def test_adrian_florin_codrianu():
	your_name = greet_adrian_florin_codrianu()
	if your_name == 'missing':
		return
	assert your_name == 'Adrian Florin Codrianu', 'Did you spell your name correctly?'

def test_stefania_croitoru():
	your_name = greet_stefania_croitoru()
	if your_name == 'missing':
		return
	assert your_name == 'Stefania Croitoru', 'Did you spell your name correctly?'

def test_tapusi_daniel_cristian_marian():
	your_name = greet_tapusi_daniel_cristian_marian()
	if your_name == 'missing':
		return
	assert your_name == 'Tapusi Daniel-Cristian-Marian', 'Did you spell your name correctly?'

def test_sara_dimoiu():
	your_name = greet_sara_dimoiu()
	if your_name == 'missing':
		return
	assert your_name == 'Sara Dimoiu', 'Did you spell your name correctly?'

def test_madalin_dina():
	your_name = greet_madalin_dina()
	if your_name == 'missing':
		return
	assert your_name == 'Madalin Dina', 'Did you spell your name correctly?'

def test_marta_dinca():
	your_name = greet_marta_dinca()
	if your_name == 'missing':
		return
	assert your_name == 'Marta Dinca', 'Did you spell your name correctly?'

def test_cristina_alexandra_draica():
	your_name = greet_cristina_alexandra_draica()
	if your_name == 'missing':
		return
	assert your_name == 'Cristina Alexandra Draica', 'Did you spell your name correctly?'

def test_violeta_ana_maria_draica():
	your_name = greet_violeta_ana_maria_draica()
	if your_name == 'missing':
		return
	assert your_name == 'Violeta Ana-Maria Draica', 'Did you spell your name correctly?'

def test_silvia_eremia():
	your_name = greet_silvia_eremia()
	if your_name == 'missing':
		return
	assert your_name == 'Silvia Eremia', 'Did you spell your name correctly?'

def test_marinela_lavinia_graure():
	your_name = greet_marinela_lavinia_graure()
	if your_name == 'missing':
		return
	assert your_name == 'Marinela Lavinia Graure', 'Did you spell your name correctly?'

def test_stefanita_ionita():
	your_name = greet_stefanita_ionita()
	if your_name == 'missing':
		return
	assert your_name == 'Ștefăniță Ioniță', 'Did you spell your name correctly?'

def test_melania_valentina_marian():
	your_name = greet_melania_valentina_marian()
	if your_name == 'missing':
		return
	assert your_name == 'Melania Valentina Marian', 'Did you spell your name correctly?'

def test_claudiu_mogodeanu():
	your_name = greet_claudiu_mogodeanu()
	if your_name == 'missing':
		return
	assert your_name == 'Claudiu Mogodeanu', 'Did you spell your name correctly?'

def test_matei_patrascu():
	your_name = greet_matei_patrascu()
	if your_name == 'missing':
		return
	assert your_name == 'Matei Patrascu', 'Did you spell your name correctly?'

def test_claudia_alexandra_pintoiu():
	your_name = greet_claudia_alexandra_pintoiu()
	if your_name == 'missing':
		return
	assert your_name == 'Claudia Alexandra Pintoiu', 'Did you spell your name correctly?'

def test_bianca_elena_popescu():
	your_name = greet_bianca_elena_popescu()
	if your_name == 'missing':
		return
	assert your_name == 'Bianca Elena Popescu', 'Did you spell your name correctly?'

def test_eduard_rosca():
	your_name = greet_eduard_rosca()
	if your_name == 'missing':
		return
	assert your_name == 'Eduard Rosca', 'Did you spell your name correctly?'

def test_mihai_alexandru_sirbu():
	your_name = greet_mihai_alexandru_sirbu()
	if your_name == 'missing':
		return
	assert your_name == 'Mihai-Alexandru Sîrbu', 'Did you spell your name correctly?'

def test_andreea___bianca_spataru():
	your_name = greet_andreea___bianca_spataru()
	if your_name == 'missing':
		return
	assert your_name == 'Andreea - Bianca Spataru', 'Did you spell your name correctly?'

def test_adriana_stanica():
	your_name = greet_adriana_stanica()
	if your_name == 'missing':
		return
	assert your_name == 'Adriana Stănică', 'Did you spell your name correctly?'

def test_apostol_stefan_alexandru():
	your_name = greet_apostol_stefan_alexandru()
	if your_name == 'missing':
		return
	assert your_name == 'Apostol Stefan Alexandru', 'Did you spell your name correctly?'

def test_alin_mihaita_stefanescu():
	your_name = greet_alin_mihaita_stefanescu()
	if your_name == 'missing':
		return
	assert your_name == 'Alin-Mihaita Stefanescu', 'Did you spell your name correctly?'

def test_andra_ioana_stoica():
	your_name = greet_andra_ioana_stoica()
	if your_name == 'missing':
		return
	assert your_name == 'Andra-Ioana Stoica', 'Did you spell your name correctly?'

def test_horia_tudor_tatu():
	your_name = greet_horia_tudor_tatu()
	if your_name == 'missing':
		return
	assert your_name == 'Horia-Tudor Tatu', 'Did you spell your name correctly?'

def test_andra_vlad():
	your_name = greet_andra_vlad()
	if your_name == 'missing':
		return
	assert your_name == 'Andra Vlad', 'Did you spell your name correctly?'

def test_catalin_constantin_vrabiuta():
	your_name = greet_catalin_constantin_vrabiuta()
	if your_name == 'missing':
		return
	assert your_name == 'Catalin-Constantin Vrabiuta', 'Did you spell your name correctly?'

def test_paul_iulian_andrei():
	your_name = greet_paul_iulian_andrei()
	if your_name == 'missing':
		return
	assert your_name == 'Paul-Iulian Andrei', 'Did you spell your name correctly?'

def test_popescu_andrei_liviu():
	your_name = greet_popescu_andrei_liviu()
	if your_name == 'missing':
		return
	assert your_name == 'Popescu Andrei Liviu', 'Did you spell your name correctly?'

def test_vlad_andrei_bacanu():
	your_name = greet_vlad_andrei_bacanu()
	if your_name == 'missing':
		return
	assert your_name == 'Vlad-Andrei Bacanu', 'Did you spell your name correctly?'

def test_stefania_bajdu():
	your_name = greet_stefania_bajdu()
	if your_name == 'missing':
		return
	assert your_name == 'Stefania Bajdu', 'Did you spell your name correctly?'

def test_cristi_daniel_bercu():
	your_name = greet_cristi_daniel_bercu()
	if your_name == 'missing':
		return
	assert your_name == 'Cristi-Daniel Bercu', 'Did you spell your name correctly?'

def test_ilinca_brezoianu():
	your_name = greet_ilinca_brezoianu()
	if your_name == 'missing':
		return
	assert your_name == 'Ilinca Brezoianu', 'Did you spell your name correctly?'

def test_razvan_andrei_cristea():
	your_name = greet_razvan_andrei_cristea()
	if your_name == 'missing':
		return
	assert your_name == 'Razvan-Andrei Cristea', 'Did you spell your name correctly?'

def test_ioana_dinu():
	your_name = greet_ioana_dinu()
	if your_name == 'missing':
		return
	assert your_name == 'Ioana Dinu', 'Did you spell your name correctly?'

def test_gorgos_felicia():
	your_name = greet_gorgos_felicia()
	if your_name == 'missing':
		return
	assert your_name == 'Gorgos Felicia', 'Did you spell your name correctly?'

def test_anca_maria_gaina():
	your_name = greet_anca_maria_gaina()
	if your_name == 'missing':
		return
	assert your_name == 'Anca-Maria Gaina', 'Did you spell your name correctly?'

def test_andreea_gherman():
	your_name = greet_andreea_gherman()
	if your_name == 'missing':
		return
	assert your_name == 'Andreea Gherman', 'Did you spell your name correctly?'

def test_tiberiu_cristian_grigorescu():
	your_name = greet_tiberiu_cristian_grigorescu()
	if your_name == 'missing':
		return
	assert your_name == 'Tiberiu-Cristian Grigorescu', 'Did you spell your name correctly?'

def test_catalin_andrei_grozavu():
	your_name = greet_catalin_andrei_grozavu()
	if your_name == 'missing':
		return
	assert your_name == 'Catalin-Andrei Grozavu', 'Did you spell your name correctly?'

def test_robert_iacob():
	your_name = greet_robert_iacob()
	if your_name == 'missing':
		return
	assert your_name == 'Robert Iacob', 'Did you spell your name correctly?'

def test_george_alexandru_marin():
	your_name = greet_george_alexandru_marin()
	if your_name == 'missing':
		return
	assert your_name == 'George Alexandru Marin', 'Did you spell your name correctly?'

def test_mara_moldoveanu():
	your_name = greet_mara_moldoveanu()
	if your_name == 'missing':
		return
	assert your_name == 'Mara Moldoveanu', 'Did you spell your name correctly?'

def test_ana_maria_nae():
	your_name = greet_ana_maria_nae()
	if your_name == 'missing':
		return
	assert your_name == 'Ana-Maria Nae', 'Did you spell your name correctly?'

def test_ionut_alexandru_netoiu():
	your_name = greet_ionut_alexandru_netoiu()
	if your_name == 'missing':
		return
	assert your_name == 'Ionut-Alexandru Netoiu', 'Did you spell your name correctly?'

def test_amalia_raluca_pencea():
	your_name = greet_amalia_raluca_pencea()
	if your_name == 'missing':
		return
	assert your_name == 'Amalia Raluca Pencea', 'Did you spell your name correctly?'

def test_darius_petriceanu():
	your_name = greet_darius_petriceanu()
	if your_name == 'missing':
		return
	assert your_name == 'Darius Petriceanu', 'Did you spell your name correctly?'

def test_darius_gabriel_petriceanu():
	your_name = greet_darius_gabriel_petriceanu()
	if your_name == 'missing':
		return
	assert your_name == 'Darius-Gabriel Petriceanu', 'Did you spell your name correctly?'

def test_ana_maria_radu():
	your_name = greet_ana_maria_radu()
	if your_name == 'missing':
		return
	assert your_name == 'Ana Maria Radu', 'Did you spell your name correctly?'

def test_gheorghe_andrei_stanciu():
	your_name = greet_gheorghe_andrei_stanciu()
	if your_name == 'missing':
		return
	assert your_name == 'Gheorghe Andrei Stanciu', 'Did you spell your name correctly?'
