# This file is autogenerated. Do not edit.
# -*- coding: utf-8 -*-

from collaboration import *

def test_rares_nicolae_achim():
	your_name = greet_rares_nicolae_achim()
	if your_name == 'missing':
		return
	assert your_name == 'Rares-Nicolae Achim', 'Did you spell your name correctly?'

def test_vlad_andrei_achim():
	your_name = greet_vlad_andrei_achim()
	if your_name == 'missing':
		return
	assert your_name == 'Vlad-Andrei Achim', 'Did you spell your name correctly?'

def test_ene_alexandru():
	your_name = greet_ene_alexandru()
	if your_name == 'missing':
		return
	assert your_name == 'Ene Alexandru', 'Did you spell your name correctly?'

def test_cristian_catalin_andrei():
	your_name = greet_cristian_catalin_andrei()
	if your_name == 'missing':
		return
	assert your_name == 'Cristian Catalin Andrei', 'Did you spell your name correctly?'

def test_cristina_andreea_antonescu():
	your_name = greet_cristina_andreea_antonescu()
	if your_name == 'missing':
		return
	assert your_name == 'Cristina Andreea Antonescu', 'Did you spell your name correctly?'

def test_cosmin_alexandru_avramescu():
	your_name = greet_cosmin_alexandru_avramescu()
	if your_name == 'missing':
		return
	assert your_name == 'Cosmin-Alexandru Avramescu', 'Did you spell your name correctly?'

def test_elena_raluca_barau():
	your_name = greet_elena_raluca_barau()
	if your_name == 'missing':
		return
	assert your_name == 'Elena-Raluca Barău', 'Did you spell your name correctly?'

def test_alexandra_beresteanu():
	your_name = greet_alexandra_beresteanu()
	if your_name == 'missing':
		return
	assert your_name == 'Alexandra Beresteanu', 'Did you spell your name correctly?'

def test_andra_maria_bighiu():
	your_name = greet_andra_maria_bighiu()
	if your_name == 'missing':
		return
	assert your_name == 'Andra-Maria Bighiu', 'Did you spell your name correctly?'

def test_alexandra_cordunasu():
	your_name = greet_alexandra_cordunasu()
	if your_name == 'missing':
		return
	assert your_name == 'Alexandra Cordunașu', 'Did you spell your name correctly?'

def test_raluca_cruceru():
	your_name = greet_raluca_cruceru()
	if your_name == 'missing':
		return
	assert your_name == 'Raluca Cruceru', 'Did you spell your name correctly?'

def test_artemiza_mihaela_dospinescu():
	your_name = greet_artemiza_mihaela_dospinescu()
	if your_name == 'missing':
		return
	assert your_name == 'Artemiza-Mihaela Dospinescu', 'Did you spell your name correctly?'

def test_mihai_dragos_andrei():
	your_name = greet_mihai_dragos_andrei()
	if your_name == 'missing':
		return
	assert your_name == 'Mihai Dragos-Andrei', 'Did you spell your name correctly?'

def test_maria_fugulin():
	your_name = greet_maria_fugulin()
	if your_name == 'missing':
		return
	assert your_name == 'Maria Fugulin', 'Did you spell your name correctly?'

def test_laurentiu_marian_gavrila():
	your_name = greet_laurentiu_marian_gavrila()
	if your_name == 'missing':
		return
	assert your_name == 'Laurentiu-Marian Gavrila', 'Did you spell your name correctly?'

def test_mihnea_stefan_ilie():
	your_name = greet_mihnea_stefan_ilie()
	if your_name == 'missing':
		return
	assert your_name == 'Mihnea-Stefan Ilie', 'Did you spell your name correctly?'

def test_stefanita_ionita():
	your_name = greet_stefanita_ionita()
	if your_name == 'missing':
		return
	assert your_name == 'Ștefăniță Ioniță', 'Did you spell your name correctly?'

def test_marian_irimia():
	your_name = greet_marian_irimia()
	if your_name == 'missing':
		return
	assert your_name == 'Marian Irimia', 'Did you spell your name correctly?'

def test_andreea_miruna_istrate():
	your_name = greet_andreea_miruna_istrate()
	if your_name == 'missing':
		return
	assert your_name == 'Andreea-Miruna Istrate', 'Did you spell your name correctly?'

def test_mihnea_gabriel_lascu():
	your_name = greet_mihnea_gabriel_lascu()
	if your_name == 'missing':
		return
	assert your_name == 'Mihnea Gabriel Lascu', 'Did you spell your name correctly?'

def test_andreea_marin():
	your_name = greet_andreea_marin()
	if your_name == 'missing':
		return
	assert your_name == 'Andreea Marin', 'Did you spell your name correctly?'

def test_andra_maslaev():
	your_name = greet_andra_maslaev()
	if your_name == 'missing':
		return
	assert your_name == 'Andra Maslaev', 'Did you spell your name correctly?'

def test_brezniceanu_mihai_cristian():
	your_name = greet_brezniceanu_mihai_cristian()
	if your_name == 'missing':
		return
	assert your_name == 'Brezniceanu Mihai Cristian', 'Did you spell your name correctly?'

def test_david_mihai_militaru():
	your_name = greet_david_mihai_militaru()
	if your_name == 'missing':
		return
	assert your_name == 'David-Mihai Militaru', 'Did you spell your name correctly?'

def test_andrei_minca():
	your_name = greet_andrei_minca()
	if your_name == 'missing':
		return
	assert your_name == 'Andrei Minca', 'Did you spell your name correctly?'

def test_ionut_pasat():
	your_name = greet_ionut_pasat()
	if your_name == 'missing':
		return
	assert your_name == 'Ionut Pasat', 'Did you spell your name correctly?'

def test_teodora_pirvan():
	your_name = greet_teodora_pirvan()
	if your_name == 'missing':
		return
	assert your_name == 'Teodora Pirvan', 'Did you spell your name correctly?'

def test_mihaela_radu():
	your_name = greet_mihaela_radu()
	if your_name == 'missing':
		return
	assert your_name == 'Mihaela Radu', 'Did you spell your name correctly?'

def test_diana_elena_rusu():
	your_name = greet_diana_elena_rusu()
	if your_name == 'missing':
		return
	assert your_name == 'Diana Elena Rusu', 'Did you spell your name correctly?'

def test_stefania_silivestru():
	your_name = greet_stefania_silivestru()
	if your_name == 'missing':
		return
	assert your_name == 'Stefania Silivestru', 'Did you spell your name correctly?'

def test_ioan_teofil_sturzoiu():
	your_name = greet_ioan_teofil_sturzoiu()
	if your_name == 'missing':
		return
	assert your_name == 'Ioan-Teofil Sturzoiu', 'Did you spell your name correctly?'

def test_daria_traicu():
	your_name = greet_daria_traicu()
	if your_name == 'missing':
		return
	assert your_name == 'Daria Traicu', 'Did you spell your name correctly?'

def test_andrei_tulpan():
	your_name = greet_andrei_tulpan()
	if your_name == 'missing':
		return
	assert your_name == 'Andrei Tulpan', 'Did you spell your name correctly?'

def test_andrei_voicu():
	your_name = greet_andrei_voicu()
	if your_name == 'missing':
		return
	assert your_name == 'Andrei Voicu', 'Did you spell your name correctly?'

def test_mihnea_vulpe():
	your_name = greet_mihnea_vulpe()
	if your_name == 'missing':
		return
	assert your_name == 'Mihnea Vulpe', 'Did you spell your name correctly?'
