# This file is autogenerated. Do not edit.
# -*- coding: utf-8 -*-

from collaboration import *

def test_laurentiu_olteanu():
	your_name = greet_laurentiu_olteanu()
	if your_name == 'missing':
		return
	assert your_name == 'Laurentiu Olteanu', 'Did you spell your name correctly?'

def test_razvan_matisan():
	your_name = greet_razvan_matisan()
	if your_name == 'missing':
		return
	assert your_name == 'Razvan Matisan', 'Did you spell your name correctly?'

def test_mara_nicolae():
	your_name = greet_mara_nicolae()
	if your_name == 'missing':
		return
	assert your_name == 'Mara Nicolae', 'Did you spell your name correctly?'

def test_diana_dutica():
	your_name = greet_diana_dutica()
	if your_name == 'missing':
		return
	assert your_name == 'Diana Dutica', 'Did you spell your name correctly?'

def test_radu_chivereanu():
	your_name = greet_radu_chivereanu()
	if your_name == 'missing':
		return
	assert your_name == 'Radu Chivereanu', 'Did you spell your name correctly?'

def test_radu_minea():
	your_name = greet_radu_minea()
	if your_name == 'missing':
		return
	assert your_name == 'Radu Minea', 'Did you spell your name correctly?'

def test_pavel_mateescu():
	your_name = greet_pavel_mateescu()
	if your_name == 'missing':
		return
	assert your_name == 'Pavel Mateescu', 'Did you spell your name correctly?'
